# Generated by Django 6.0 on 2025-12-16 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khach_san', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach', models.CharField(max_length=100)),
                ('loai_khach', models.CharField(choices=[('vang_lai', 'Vãng lai'), ('tour', 'Khách tour đoàn'), ('booking', 'Booking'), ('agoda', 'Agoda'), ('traveloka', 'Traveloka')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhan', models.DateField()),
                ('ngay_tra', models.DateField(blank=True, null=True)),
                ('dang_o', models.BooleanField(default=True)),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khach_san.phong')),
                ('khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dat_phong.khach')),
            ],
        ),
    ]
