# Generated by Django 6.0 on 2025-12-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_phong', '0001_initial'),
        ('khach_san', '0002_loaiphong_gia_mot_dem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datphong',
            name='khach',
        ),
        migrations.AddField(
            model_name='datphong',
            name='loai_khach',
            field=models.CharField(choices=[('vang_lai', 'Vãng lai'), ('tour', 'Khách tour đoàn'), ('booking', 'Booking'), ('agoda', 'Agoda'), ('traveloka', 'Traveloka')], default='vang_lai', max_length=20, verbose_name='Loại khách'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datphong',
            name='ten_khach',
            field=models.CharField(default='vang_lai', max_length=100, verbose_name='Tên khách'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datphong',
            name='dang_o',
            field=models.BooleanField(default=True, verbose_name='Đang ở'),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='ngay_nhan',
            field=models.DateField(verbose_name='Ngày nhận phòng'),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='ngay_tra',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày trả phòng'),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='phong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khach_san.phong', verbose_name='Phòng'),
        ),
        migrations.DeleteModel(
            name='Khach',
        ),
    ]
