# Generated by Django 6.0 on 2025-12-22 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_phong', '0002_remove_datphong_khach_datphong_loai_khach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dich_vu', models.CharField(max_length=100)),
                ('gia', models.PositiveIntegerField()),
                ('don_vi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuDungDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('thoi_diem', models.DateTimeField(auto_now_add=True)),
                ('dat_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dat_phong.datphong')),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dat_phong.dichvu')),
            ],
        ),
    ]
