# Generated by Django 6.0 on 2025-12-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_phong', '0003_dichvu_sudungdichvu'),
    ]

    operations = [
        migrations.AddField(
            model_name='datphong',
            name='ma_khach',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='Mã khách'),
        ),
    ]
