# Generated by Django 6.0 on 2025-12-22 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_phong', '0004_datphong_ma_khach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datphong',
            options={'ordering': ['-dang_o', '-ngay_nhan']},
        ),
        migrations.AddField(
            model_name='datphong',
            name='ngay_tra_du_kien',
            field=models.DateField(default=datetime.date(2025, 12, 22), verbose_name='Ngày trả dự kiến'),
            preserve_default=False,
        ),
    ]
