# Generated by Django 6.0 on 2025-12-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phong', models.CharField(max_length=10, unique=True)),
                ('trang_thai', models.CharField(choices=[('trong', 'Trống'), ('dang_thue', 'Đang thuê'), ('dang_bao_tri', 'Đang bảo trì')], default='trong', max_length=20)),
                ('loai_phong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khach_san.loaiphong')),
            ],
        ),
    ]
