# Generated by Django 6.0 on 2025-12-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khach_san', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaiphong',
            name='gia_mot_dem',
            field=models.PositiveIntegerField(default=500000, verbose_name='Giá / đêm (VND)'),
            preserve_default=False,
        ),
    ]
