# Generated by Django 6.0 on 2025-12-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dat_phong', '0005_alter_datphong_options_datphong_ngay_tra_du_kien'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tien_phong', models.PositiveIntegerField(default=0)),
                ('tien_dich_vu', models.PositiveIntegerField(default=0)),
                ('tong_tien', models.PositiveIntegerField(default=0)),
                ('trang_thai', models.CharField(choices=[('chua_tt', 'Chưa thanh toán'), ('da_tt', 'Đã thanh toán')], default='chua_tt', max_length=10)),
                ('thoi_diem_tao', models.DateTimeField(auto_now_add=True)),
                ('dat_phong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='dat_phong.datphong', verbose_name='Đặt phòng')),
            ],
        ),
    ]
